title: Malvo's Blog
author: Malvo
email: devilmares@gmail.com
description: >-
  先完成，再完美。
baseurl: ""
url: "https://chdwql.github.io"

# Theme settings
remote_theme: brianmaierjr/long-haul

# Long Haul specific settings
paginate: 20
paginate_path: "/blog/page:num/"
permalink: /blog/:title/

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about.html

social:
    github: chdwql
    email: devilmares@gmail.com

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-paginate

# Build settings
future: true

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
