title: Malvo's Blog
author: Malvo
email: devilmares@gmail.com
description: >-
  先完成，再完美。
baseurl: ""
url: "https://chdwql.github.io"

# Theme settings
remote_theme: riggraz/no-style-please

theme_config:
  show_description: true

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

# Build settings
future: true
timezone: Asia/Shanghai

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
